-- CreateEnum
CREATE TYPE "TypeDroitCode" AS ENUM ('ADMIN', 'READ', 'WRITE');

-- CreateEnum
CREATE TYPE "DroitCode" AS ENUM ('CREATE', 'DELETE', 'READ', 'UPDATE');

-- CreateEnum
CREATE TYPE "TypeUtilisateurCode" AS ENUM ('ADMIN', 'CLIENT', 'GEST');

-- CreateTable
CREATE TABLE "TypeDroit" (
    "TDR_CODE" "TypeDroitCode" NOT NULL,
    "TDR_LIBELLE" TEXT NOT NULL,
    "DRO_CODE" TEXT NOT NULL,

    CONSTRAINT "TypeDroit_pkey" PRIMARY KEY ("TDR_CODE")
);

-- CreateTable
CREATE TABLE "Droit" (
    "DRO_CODE" "DroitCode" NOT NULL,
    "DRO_LIBELLE" TEXT NOT NULL,
    "TDR_CODE" "TypeDroitCode" NOT NULL,
    "PRO_ID" INTEGER NOT NULL,

    CONSTRAINT "Droit_pkey" PRIMARY KEY ("DRO_CODE")
);

-- CreateTable
CREATE TABLE "Profil" (
    "PRO_ID" SERIAL NOT NULL,
    "PRO_LIBELLE" TEXT NOT NULL,
    "DRO_CODE" TEXT NOT NULL,
    "PRO_DATE_CREATION" TIMESTAMP(3) NOT NULL,
    "PRO_DATE_MODIFICATION" TIMESTAMP(3) NOT NULL,
    "UTI_ID" INTEGER NOT NULL,

    CONSTRAINT "Profil_pkey" PRIMARY KEY ("PRO_ID")
);

-- CreateTable
CREATE TABLE "TypeUtilisateur" (
    "TUT_CODE" "TypeUtilisateurCode" NOT NULL,
    "TUT_LIBELLE" TEXT NOT NULL,
    "UTI_ID" INTEGER NOT NULL,

    CONSTRAINT "TypeUtilisateur_pkey" PRIMARY KEY ("TUT_CODE")
);

-- CreateTable
CREATE TABLE "Utilisateur" (
    "UTI_ID" SERIAL NOT NULL,
    "UTI_NOM" TEXT NOT NULL,
    "UTI_PRENOM" TEXT NOT NULL,
    "UTI_EMAIL" TEXT NOT NULL,
    "UTI_DATE_NAISSANCE" TIMESTAMP(3) NOT NULL,
    "UTI_ADRESSE" TEXT NOT NULL,
    "UTI_ACTIF" BOOLEAN NOT NULL,
    "PRO_ID" INTEGER NOT NULL,
    "TUT_CODE" "TypeUtilisateurCode" NOT NULL,
    "UTI_DATE_CREATION" TIMESTAMP(3) NOT NULL,
    "UTI_DATE_MODIFICATION" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Utilisateur_pkey" PRIMARY KEY ("UTI_ID")
);

-- AddForeignKey
ALTER TABLE "Droit" ADD CONSTRAINT "Droit_TDR_CODE_fkey" FOREIGN KEY ("TDR_CODE") REFERENCES "TypeDroit"("TDR_CODE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Utilisateur" ADD CONSTRAINT "Utilisateur_PRO_ID_fkey" FOREIGN KEY ("PRO_ID") REFERENCES "Profil"("PRO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Utilisateur" ADD CONSTRAINT "Utilisateur_TUT_CODE_fkey" FOREIGN KEY ("TUT_CODE") REFERENCES "TypeUtilisateur"("TUT_CODE") ON DELETE RESTRICT ON UPDATE CASCADE;
